config/routes.rb
DeporteConex::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  get "developer_logout" => "developer_sessions#destroy", as: :developer_session_end
  get "lockpage/" => "developer_sessions#lockpage", as: :developer_lock
  get "auth/twitter", as: :developer_login
  get "auth/twitter/callback" => "developer_sessions#create"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :developer_session, if: -> { check_staging } 

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  private 
  
  def developer_session
    # p "Developer name found in session: #{session[:developer_name]}"
    # p ENV["DEVELOPERS"]
    if session[:developer_name].nil?
      redirect_to developer_lock_path
    end
  end

  def check_staging
    # p ">>> Checking for staging environment..."
    !(ENV["STAGINGTWITTERAPIKEY"].empty?) 
  end

end

app/controllers/developer_sessions_controller.rb
class DeveloperSessionsController < ApplicationController
  skip_before_action :developer_session, :only => [:create, :lockpage]
  layout false

  def lockpage
  end

  def destroy
    reset_session
    redirect_to root_url
  end
	
  def create
    # raise request.env["omniauth.auth"].to_yaml
    auth = request.env["omniauth.auth"]
    name = auth["info"]["nickname"]
    
    if ENV["DEVELOPERS"].include?(name.to_s)
      session[:developer_name] = name
      redirect_to root_url
    else
      # at some point we should log bad access attempts and block bad IPs that try to log in too much (if that ever happens)
      redirect_to developer_lock_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = session[:developer_name]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

  def create
    if params[:role].present?
      super
      resource.add_role(params[:role])
      params.each do |key,value|
        Rails.logger.warn "Param #{key}: #{value}"
      end
    else
      redirect_to new_user_registration_path, :notice => "You need to select a role!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/developer_sessions_helper.rb
module DeveloperSessionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/developer_sessions/lockpage.html.erb
<h2>Staging environment login</h2>

<%= link_to "Twitter Login", developer_login_path %> 

app/views/home/index.html.erb
<div class="row">
    <div id="banner">
        <div id="banner-content">
            <h3 class="text-center">Beta access coming soon - Sign up for a chance at the first preview!</h3>
	    <!-- This is all really ugly and needs to be changed. Maybe a developer bar somewhere around here?-->
	    <p>Welcome <%= @user %></p>
	    <%= link_to "Destroy Session", developer_session_end_path %>
        </div>
    </div>
</div>
<div class="container container-home">
<div class="jumbotron jumbotron-home">
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="/"><%= image_tag "logo-lg.png", class: "logo" %></a>
                <p>DeporteConex helps connect international student athletes with American university sports recruiters with the aim of making scholarship opportunities possible.</p>
        </div>
        <div class="col-md-12">
            <div class="video-container">
                <iframe width="100%" height="525" frameborder="0" allowfullscreen="" src="//www.youtube.com/embed/HRVq43fZpXU?rel=0"></iframe>
            </div>
        </div>
    </div>
</div>

<!-- TABS BLOCK BEGIN -->
<div class="row">

        <div class="panel panel-default">
            <div class="panel-heading"><h2 class="text-center">Athletes and Parents</h2></div>
          <div class="panel-body">


            <h3>What we do</h3>
            <p>We offer a recruiting platform which connects international student-athletes with American university coaches and scouts. The connections on our recruiting platform may lead to more exposure, athletic scholarships, and greater future opportunities for registered student-athletes.

                <h3>What can you expect?</h3>
                <div class="row text-center">
                    <div class="col-md-4">
                    <%= fa_icon "group 4x" %>
                    <br />
                    <p>Your own personal student-athlete profile
                    </div>
                    <div class="col-md-4">
                    <%= fa_icon "star 4x" %>
                    <br />
                    <p>Premium features including video, references, and letters of interest
                    </div>
                    <div class="col-md-4">
                    <%= fa_icon "dot-circle-o 4x" %>
                    <br />
                    <p>Recruiting information and advanced scouting by our supporters at the NCSA
                    </div>
                </div>
                We cannot guarantee a student-athlete will receive an athletic scholarship. We can guarantee however, that we will work everyday to provide every student-athlete the chance to be noticed and recruited.
                <br></br>
                <div class="text-center col-md-4">
                <%= link_to 'Sign up Now', new_user_registration_path, class: "btn btn-warning btn-lg btn-block" %>
                </div>
                <p>Your path to being recruited starts here. It is free and takes less than two minutes. Reserve your profile today and show your commitment to university coaches and recruiters!
            </div>
        </div>
</div>

<div class="row">

                    <div class="panel panel-default">
                        <div class="panel-heading"><h2 class="text-center">Coaches and Scouts</h2></div>
            <div class="panel-body">
                <div class="col-md-8">
                    <h3>What’s in it for you?</h3>
                    <div class="row text-center">
                    <div class="col-md-4">
                    <%= fa_icon "clock-o 4x" %>
                    </br />
                    <p>Reduce time and stress finding athletes, spend more time evaluating and connecting with talented recruits
                    </div>
                    <div class="col-md-4">
                    <%= fa_icon "globe 4x" %>
                    </br />
                    <p>Large and unique talent pool to recruit from
                    </div>
                    <div class="col-md-4">
                    <%= fa_icon "search 4x" %>
                    </br />
                    <p>Easily search and track talented and qualified student-athletes
                    </div>

                </div>
                    <br />
                    College sports are incredibly competitive, and it all begins with recruiting. Deporte Conex offers the chance to view, evaluate, and connect with talented recruits at a click of the button. We help you reduce time and reduce stress from the typically complicated and fast-paced recruiting battle.
                    <br></br>
                    We help you uncover new talent and build impressive recruiting classes. Stop missing out on talented athletes and let us help you win the recruiting battle!
                    <br></br>
                    </div>
                    <div class="col-md-4">
                    <h3>Why international talent?</h3>

                    Consider the following:
                    <br></br>

                    In 2008 16,000 international student-athletes played at NCAA schools with 70% of them playing at Division I schools. The number of international student-athletes playing intercollegiate sports has been increasing every year!
                    <br></br>

                    Physical location is no longer a limitation. Stop missing out on incredible talent and let us help you connect with athletes all over the world!
                    <br></br>

                    <p>It’s free and takes less than 2 minutes.
                        <br />
                    <div class="text-center">
                    <%= link_to 'Sign up Now', new_user_registration_path, class: "btn btn-warning btn-lg btn-block" %>
                </div>
                </div>
                    </div></div>
                </div>
<!-- TABS BLOCK END -->
</div>

app/views/layouts/_footer.html.erb
    <div class="container">
    <section id="contact_us" class="box">
        <div class="center">
            <h2 class="text-center">Contact us</h2>
            <div class="contact_info" itemscope="" itemtype="http://schema.org/Organization">
                <ul>
                    <li itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
                        <span class="fa fa-map-marker"></span>
                        <span itemprop="streetAddress">2001 SW 27th Ave</span>,
                        <span itemprop="postalCode">33145</span>,
                        <span itemprop="addressLocality">Miami, FL</span>
                    </li>
                    <li itemprop="email">
                         <span class="fa fa-envelope"> </span>support@deporteconex.com</li>
                    <li itemprop="telephone">
                         <span class="fa fa-phone"> </span>1(855) 983-2916</li>
                    <li>
                         <span class="fa fa-twitter"> </span>@deporteconex</li>
                </ul>
            </div>

            <div class="map" id="map-canvas" style="position: relative; background-color: rgb(229, 227, 223); overflow: hidden; -webkit-transform: translateZ(0);">
                <iframe src="https://www.google.com/maps/embed?pb=!1m5!3m3!1m2!1s0x88d9b7ae9eaeda97%3A0x676512151d8bc78b!2s2001+SW+27th+Ave%2C+Miami%2C+FL+33145%2C+USA!5e0!3m2!1sen!2sca!4v1390002389549" width="730" height="250" frameborder="0" style="border:0"></iframe>
            </div>
        </div>
    </section>

<!-- CONTACT US BLOCK END -->
<!-- FOOTER BLOCK BEGIN -->
</div>
    <div class="footerHeight"></div>
    <div id="footer">
        <div class="container center">
            <!-- Social icons -->
            <div class="socials">
                <ul>
                    <!-- <li>
                        <a href="http://dribbble.com/" target="_blank" title="Dribbble" class="fa fa-dribbble"></a>
                    </li> -->
                    <li>
                        <a href="https://plus.google.com/116429347373126870669" rel="publisher" target="_blank" title="Google+" class="fa fa-google-plus"></a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/DeporteConex" target="_blank" title="Facebook" class="fa fa-facebook"></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/DeporteConex" target="_blank" title="Twitter" class="fa fa-twitter"></a>
                    </li>
                </ul>
            </div>
            <div class="copyright">
                <p>© Copyright 2014 Deporte Conex.
                    <br>All Rights Reserved.</p>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container ">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a title="Deporte Conex" class="navbar-brand logo-wrapper" href="/"><%= image_tag "logo.png", class: "logo" %></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right utility-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Deporte Conex" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Deporte Conex" %>">
    <link rel="shortcut icon" href="/favicon.ico">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main class="container" role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>

    <script type="text/javascript">
      $(function(){
        $(".player").mb_YTPlayer();
      });
    </script>
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>